//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDMS.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drawing
    {
        public decimal Id { get; set; }
        public string PONo { get; set; }
        public string FileNo { get; set; }
        public string DrawingNo { get; set; }
        public string Subject { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public string ApprovalBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FilePath { get; set; }
        public Nullable<decimal> POId { get; set; }
    }
}
