//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDMS.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementOrder
    {
        public int Id { get; set; }
        public string OrderNo { get; set; }
        public string Subject { get; set; }
        public System.DateTime Date { get; set; }
        public string InspectorName { get; set; }
        public string Designation { get; set; }
        public string FirmName { get; set; }
        public System.DateTime OnwardStartDate { get; set; }
        public System.DateTime OnwardEndDate { get; set; }
        public string OnwordFrom { get; set; }
        public string OnwordTo { get; set; }
        public string OnwordModeOfTravel { get; set; }
        public System.DateTime ReturnStartDate { get; set; }
        public System.DateTime ReturnEndDate { get; set; }
        public string ReturnFrom { get; set; }
        public string ReturnTo { get; set; }
        public string ReturnModeOfTravel { get; set; }
        public string SigningAuthority { get; set; }
        public string SADesignation { get; set; }
        public string Distribution { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public string Flag { get; set; }
    }
}
