//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDMS.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POGeneration
    {
        public int Id { get; set; }
        public int PO_ID { get; set; }
        public Nullable<int> FCL { get; set; }
        public Nullable<int> PO_CORRESPONDENCE { get; set; }
        public Nullable<int> DRAWING { get; set; }
        public Nullable<int> QAP { get; set; }
        public Nullable<int> I_NOTE { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
