//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDMS.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyLetter
    {
        public decimal id { get; set; }
        public string Year { get; set; }
        public string IssuingAuthority { get; set; }
        public string PLNo { get; set; }
        public string Subject { get; set; }
        public System.DateTime Date { get; set; }
        public string FilePath { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
