//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDMS.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int Id { get; set; }
        public string FileNo { get; set; }
        public string PONo { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<decimal> POValue { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> NoOfLots { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string PoPlacingAuthority { get; set; }
        public string Inspectors { get; set; }
        public string Firm { get; set; }
        public string FirmAddress { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string Flag { get; set; }
        public string Subject { get; set; }
        public string Equipment { get; set; }
        public string SparesFor { get; set; }
    }
}
