//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDMS.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QAP
    {
        public int Id { get; set; }
        public string PONo { get; set; }
        public string FileNo { get; set; }
        public string QAPNo { get; set; }
        public string Subject { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public string ApprovedBy { get; set; }
        public string DrawingNoRef { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<decimal> POId { get; set; }
    }
}
