//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INDMS.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standard
    {
        public decimal Id { get; set; }
        public string StandardNo { get; set; }
        public string Year { get; set; }
        public string Revision { get; set; }
        public string SubjectParam { get; set; }
        public string Subject { get; set; }
        public string Type { get; set; }
        public string FilePath { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
